[env:esp32dev]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -Os
    -DCORE_DEBUG_LEVEL=0
build_unflags = -flto

lib_deps =
    sparkfun/SparkFun SCD4x Arduino Library
    olikraus/U8g2
    Wire
    me-no-dev/ESP Async WebServer@^1.2.3
    me-no-dev/AsyncTCP@^1.1.1
    bblanchon/ArduinoJson@^7.0.0